"""new tables added for the convesation feedback

Revision ID: 47fbe0df19f8
Revises: 22ecceff3e69
Create Date: 2022-12-10 14:44:37.122368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fbe0df19f8'
down_revision = '22ecceff3e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('feedback_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users_unknown_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('unknown_question', sa.Text(), nullable=False),
    sa.Column('question_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_unknown_questions')
    op.drop_table('users_feedback')
    # ### end Alembic commands ###
