"""user audio table added

Revision ID: 71f411988628
Revises: b6cbd5cc3c65
Create Date: 2022-12-05 12:43:56.600475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f411988628'
down_revision = 'b6cbd5cc3c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_audio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('userAudioPath', sa.Text(), nullable=True),
    sa.Column('userAudioGMMPath', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_audio')
    # ### end Alembic commands ###
