"""userTable struture changed

Revision ID: e37eb7fb6240
Revises: ec179a4cd3df
Create Date: 2022-12-02 11:12:53.121695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e37eb7fb6240'
down_revision = 'ec179a4cd3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userImg_mimetype')
    op.drop_column('users', 'userImg')
    op.drop_column('users', 'userAudioLocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userAudioLocation', mysql.TEXT(), nullable=False))
    op.add_column('users', sa.Column('userImg', mysql.TEXT(), nullable=False))
    op.add_column('users', sa.Column('userImg_mimetype', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
